# Generated by Django 3.2.9 on 2021-11-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficce_contact',
            name='icons',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
