# Generated by Django 3.2.9 on 2021-11-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0003_blog_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(null=True, upload_to='video/', verbose_name=''),
        ),
    ]
